export const appConstants = {
  SET_AUTH_STATE: 'SET_AUTH_STATE',
  SET_USER_LIST: 'SET_USER_LIST',
  SET_LOADER_STATE: 'SET_LOADER_STATE',
  SET_DRAWER_STATE: 'SET_DRAWER_STATE',
  SET_SCREEN_TYPE: 'SET_SCREEN_TYPE',
};
