export const English = {
  auth: {
    login: {
      heading: 'Sign In',
      subHeading: 'Sign in to your account',
      provider: {
        google: 'Sign in with Google',
        apple: 'Sign in with Apple',
      },
      forgotPassword: 'Forgot password?',
      signIn: 'Sign In',
      message: "Don't have an account?",
      register: 'Register',
    },
    signup: {
      heading: 'Create an account',
      subHeading: 'Create an account to use dashboard',
      provider: {
        google: 'Sign up with Google',
        apple: 'Sign up with Apple',
      },
      terms: 'I agree the',
      conditions: 'terms and conditions',
      signUp: 'Sign Up',
      message: 'Already have an account?',
      signin: 'Sign in here',
    },
    logout: 'Logout',
    labels: {
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email address',
      phoneNumber: 'Phone Number',
      dob: 'Date of Birth',
      address: 'Address',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      password: 'Password',
      cPassword: 'Confirm Password',
    },
  },
  dashboard: {
    dash: 'Dash.',
    search: 'Search...',
    activities: 'Activities',
    activityDate: 'May - June 2021',
    products: 'Top Products',
    schedules: "Today's Schedules",
    seeAll: 'See All',
    drawer: {
      help: 'Help',
      contact: 'Contact Us',
    },
    users: {
      filter: 'Filter',
      add: 'Add',
      search: 'Search in table...',
      searchNotFound: 'Search Query Not Found!',
      userListEmpty: 'No Data Found!',
      modalTitle: 'Users Filter',
    },
    settings: {
      profile: 'Profile',
      account: 'Account',
      tFA: '2-Step Verification',
      danger: 'Danger Zone',
      deleteAccount: 'Delete My Account',
      security: 'Security',
      save: 'Save',
      change: 'Change',
    },
  },
};
